version: '3'

services:  

  web:
    build: .
    command: ./run_gunicorn.sh
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CELERY_BACKEND=redis://redis:6379
      - CELERY_BROKER=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis
    depends_on:
      - postgres

  celery_worker:
    build: .
    command: ./run_celery_worker.sh
    volumes:
      - .:/app
    links:
      - postgres
      - redis
    depends_on:
      - redis
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres03
      - POSTGRES_USER=dishes_admin
      - POSTGRES_PASSWORD=123456
  redis:
    image: redis
volumes:
    postgres_data: