# Generated by Django 2.1.7 on 2019-02-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(
                default='None', related_name='dishes', to='coocking_book.Ingredient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ingredients',
            field=models.ManyToManyField(
                default='None', related_name='orders', to='coocking_book.IngredientInOrder'),
        ),
    ]
