# Generated by Django 2.1.5 on 2019-02-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0002_auto_20190203_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
