# Generated by Django 2.1.7 on 2019-02-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0003_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(
                related_name='dishes', to='coocking_book.Ingredient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ingredients',
            field=models.ManyToManyField(
                related_name='orders', to='coocking_book.IngredientInOrder'),
        ),
    ]
