# Generated by Django 2.1.5 on 2019-02-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0004_auto_20190203_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(
                related_name='dishes', to='coocking_book.Ingredient'),
        ),
    ]
