# Generated by Django 2.1.5 on 2019-02-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0005_auto_20190203_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now=True)),
                ('ingredients', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='coocking_book.Ingredient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='OrderList', to='coocking_book.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_list',
            field=models.ManyToManyField(
                related_name='orders', through='coocking_book.OrderList', to='coocking_book.Ingredient'),
        ),
    ]
