# Generated by Django 2.1.5 on 2019-02-05 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0006_auto_20190205_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='OrderLists', to='coocking_book.Order'),
        ),
    ]
