# Generated by Django 2.1.5 on 2019-02-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0007_auto_20190205_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.FloatField(
                blank=True, null=True, verbose_name='Количество в граммах'),
        ),
    ]
