# Generated by Django 2.1.5 on 2019-02-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0008_auto_20190205_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_list',
        ),
        migrations.AddField(
            model_name='order',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ingredients',
            field=models.ManyToManyField(
                related_name='orders', to='coocking_book.Ingredient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
