# Generated by Django 2.1.5 on 2019-02-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0009_auto_20190205_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.FloatField(verbose_name='Количество в граммах'),
        ),
    ]
