# Generated by Django 2.1.5 on 2019-02-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0010_auto_20190206_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coocking_book.Ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_dish', to='coocking_book.Dish'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderingredients',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ingredients', to='coocking_book.Order'),
        ),
    ]
