# Generated by Django 2.1.5 on 2019-02-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coocking_book', '0011_auto_20190208_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
